#!/bin/sh

VERSION="5.7.0"
RELEASE="3"
CHANGELOG="KDE Frameworks ${VERSION}"
AUTHOR="Daniel Vrátil <dvratil@redhat.com>"

#REMOVE_DGROC_CHANGELOG="TRUE"

URL="http://pub.dvratil.cz/pub/kf5/srpm/$VERSION"


dt=`date +'%a %b %d %Y'`

for tier in tier{1,2,3,4}; do
  for fw in `/usr/bin/ls -1 $tier`; do
    sed -i 's/^Version:        [0-9\.]*$/Version:        '"$VERSION"'/' $tier/$fw/$fw.spec
    sed -i 's/^Release:        [0-9a-z\.]*/Release:        '"$RELEASE"'/' $tier/$fw/$fw.spec
#    sed -i 's/^Source0:        http:\/\/download.kde.org\/unstable\//Source0:        http:\/\/download.kde.org\/stable\//' $tier/$fw/$fw.spec
#    sed -i 's/^\%changelog/\%changelog\n\* '"$dt"' '"$AUTHOR"' - '"$VERSION"'-'"$RELEASE"'\n- '"$CHANGELOG"'\n/' $tier/$fw/$fw.spec
#
#    # This beast matches changelog lines generated by dgroc-kf5 and removes them
#    if [ -n "$REMOVE_DGROC_CHANGELOG" ]; then
#        sed  ':a;N;$!ba;s/\* \(Mon\|Tue\|Wed\|Thu\|Fri\|Sat\|Sun\) \(Jan\|Feb\|Mar\|Apr\|May\|Jun\|Jul\|Aug\|Sep\|Oct\|Nov\|Dec\) [0-9]* [0-9]* dvratil <dvratil@redhat.com> - \([0-9a-z\.-]*\)\n- [a-zA-Z0-9\:\ ]*\n\n//g'
#    fi
#
    rpmbuild -bs $tier/$fw/$fw.spec

  done
done

for tier in tier{1,2,3,4}; do
  for fw in `/usr/bin/ls -1 $tier`; do
    scp $HOME/rpmbuild/SRPMS/$fw-$VERSION-$RELEASE.fc21.src.rpm dvratil.cz:pub/kf5/srpm/$VERSION
  done
done

for tier in tier{1,2,3,4}; do
  for fw in `/usr/bin/ls -1 $tier`; do
    echo "$URL/$fw-$VERSION-$RELEASE.fc21.src.rpm";
  done
done

echo "Remember to update kf5 and extra-cmake-modules first!"

