#!/bin/sh

#
# Copyright (C) 2015  Daniel Vrátil <dvratil@redhat.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#


# TODO: Make this a Python script to run together with cmake-to-rpm-deps.py


VERSION="5.9.0"
RELEASE="1"
CHANGELOG="KDE Frameworks ${VERSION}"
AUTHOR="Daniel Vrátil <dvratil@redhat.com>"

#REMOVE_DGROC_CHANGELOG="TRUE"
DRY_RUN="TRUE"

dt=`date +'%a %b %d %Y'`

basedir=`pwd`

ssh-add $HOME/.ssh/id_rsa.redhat

for tier in tier1 tier2 tier3 tier4; do
  cd ${basedir}
  for fw in `/usr/bin/ls -1 $tier`; do
    cd ${basedir}/${tier}/${fw}
    echo "======= Tier ${tier}: ${fw} ========"
    for branch in f20 f21 f22 master; do
        git checkout $branch
        git pull
    done

    sed -i 's/^Version:        [0-9\.]*$/Version:        '"$VERSION"'/' $fw.spec
    sed -i 's/^Release:        [0-9a-z\.]*/Release:        '"$RELEASE"'/' $fw.spec
    #sed -i 's/^Source0:        [0-9a-zA-Z_-\.%]*/Source0:        http:\/\/download.kde.org\/unstable\/frameworks\/\%{version}\/\%{framework}-\%{version}.tar.xz/' $fw.spec
    #sed -i 's/^Source0:        http:\/\/download.kde.org\/unstable\//Source0:        http:\/\/download.kde.org\/stable\//' $fw.spec
    #sed -i 's/%{stable}\/frameworks\/%{version}\//%{stable}\/frameworks\/%{versiondir}\//' $fw.spec
    sed -i 's/^\%changelog/\%changelog\n\* '"$dt"' '"$AUTHOR"' - '"$VERSION"'-'"$RELEASE"'\n- '"$CHANGELOG"'\n/' $fw.spec

    # This beast matches changelog lines generated by dgroc-kf5 and removes them
    #if [ -n "$REMOVE_DGROC_CHANGELOG" ]; then
    #    sed  -i ':a;N;$!ba;s/\* \(Mon\|Tue\|Wed\|Thu\|Fri\|Sat\|Sun\) \(Jan\|Feb\|Mar\|Apr\|May\|Jun\|Jul\|Aug\|Sep\|Oct\|Nov\|Dec\) [0-9]* [0-9]* dvratil <dvratil@redhat.com> - \([0-9a-z\.-]*\)\n- [a-zA-Z0-9\:\ ]*\n\n//g' $fw.spec
    #fi

    spectool -g -R $fw.spec
    srcurl=`spectool -s 0 $fw.spec`
    srcname=${srcurl##*/}
    fedpkg new-sources $HOME/rpmbuild/SOURCES/$srcname
    git add $fw.spec .gitignore sources
    git commit -m "${CHANGELOG}"
    # TODO: Make this smarter
    for branch in f22 f21 f20; do
        git checkout $branch
        git merge master
    done
    #if [ -n "$DRY_RUN" ]; then
    #    git push --all origin
    #fi
    #git checkout master
    #git push --all origin
  done
done

